---
editor_options: 
  markdown: 
    wrap: 72
---

# Downloading the gene_expression.tsv file

download.file("<https://raw.githubusercontent.com/ghazkha/Assessment4/refs/heads/main/gene_expression.tsv>",
"gene_expression.tsv")

# Install and load required packages

if (!require("seqinr")) install.packages("seqinr")

# Load seqinr package

library(seqinr)

# Read downloaded file

gene_expression \<- read.table("gene_expression.tsv", header = TRUE, sep
= "\t", row.names = 1) head(gene_expression)

# new column with the mean of the other columns

gene_expression\$Mean \<- rowMeans(gene_expression)
head(gene_expression)

# List of 10 genes with the highest mean expression

top_10_genes \<- head(gene_expression[order(-gene_expression\$Mean), ],
10) top_10_genes

# number of genes with a mean expression \< 10

low_mean_genes \<- sum(gene_expression\$Mean \< 10) low_mean_genes

# histogram of mean values

hist(gene_expression\$Mean, main = "Histogram of Gene Expression Means",
xlab = "Mean Expression")

# Downloading the growth_data.csv file

download.file("<https://raw.githubusercontent.com/ghazkha/Assessment4/refs/heads/main/growth_data.csv>",
"growth_data.csv")

# Read and inspect the "growth_data.csv" file

growth_data \<- read.csv("growth_data.csv") colnames(growth_data)

# mean and standard deviation  of both sites

aggregate(cbind(Circumf_2005_cm, Circumf_2020_cm) ~ Site, data = growth_data, FUN = function(x) c(mean = mean(x), sd = sd(x)))

# boxplot of tree circumferences at the start and end of the study for both sites
boxplot(Circumf_2005_cm ~ Site, data = growth_data, 
        main = "Tree Circumference in 2005 by Site", xlab = "Site", ylab = "Circumference (cm)")

boxplot(Circumf_2020_cm ~ Site, data = growth_data, 
        main = "Tree Circumference in 2020 by Site", xlab = "Site", ylab = "Circumference (cm)")

# mean growth over the last 10 years (2010-2020) at each site
growth_data$Growth_10_years <- growth_data$Circumf_2020_cm - growth_data$Circumf_2010_cm aggregate(Growth_10_years ~ Site, data = growth_data, mean)

# t-test to estimate if the 10-year growth differs between the two sites
t_test_growth <- t.test(Growth_10_years ~ Site, data = growth_data)
t_test_growth$p.value

